# Change these first
owner: TMRRWinc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Lambton Public Health
    url: https://lambtonpublichealth.ca
  - name: Minds Connected
    url: https://mindsconnected.ca
  - name: Judith & Norman Alix Foundation
    url: https://jnaf.ca

status-website:
  themeUrl: https://rawcdn.githack.com/TMRRWinc/status/8c47484745dfddee48c364a45242ecdb9d0e4476/assets/css/tmrrw.css
  cname: uptime.tmrrwinc.com
  logoUrl: https://uploads-ssl.webflow.com/62d03a0ddfe41e0b5dca9c5b/62d03a0ddfe41e8104ca9c9b_footer-logo.svg
  name: " "
  introTitle: "**Uptime Monitor**"
  introMessage: A powerful tool that ensures the continuous availability and performance of our services. With real-time data updates, you can stay informed about any issues or downtime that may occur. Our uptime monitor helps us strive for optimal service reliability.
  navbar:
    - title: Get Support
      href: https://tmrrwinc.com/support
  js: "window.onload = function() { document.querySelector(a.logo).setAttribute('href', 'https://tmrrwinc.com'); }"
  favicon: https://uploads-ssl.webflow.com/62d03a0ddfe41e0b5dca9c5b/62d579f0038ebadc629dc04f_TMRRW-Creative-Favicon%20-32.png

i18n:
  footer: This page is open source, powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
