# Change these first
owner: TMRRWinc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Lambton Public Health
    url: https://lambtonpublichealth.ca

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.tmrrwinc.com
  # baseUrl: /your-repo-name
  logoUrl: https://uploads-ssl.webflow.com/62d03a0ddfe41e0b5dca9c5b/62d03a0ddfe41e8104ca9c9b_footer-logo.svg
  name: Website Uptime Monitoring
  introTitle: "**TMRRW Inc. Uptime Monitor** is a powerful tool that ensures the continuous availability and performance of our services"
  introMessage: With real-time data updates, you can stay informed about any issues or downtime that may occur. Our uptime monitor helps us strive for optimal service reliability.
  navbar:
    - title: Status
      href: /
    - title: Support
      href: https://tmrrwinc.com/support

i18n:
  footer: This page is [open source](https://tmrrwinc.com), powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
