# Change these first
owner: TMRRWinc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Lambton Public Health
    url: https://lambtonpublichealth.ca
  - name: Minds Connected
    url: https://mindsconnected.ca
  - name: Judith Normal Alix Foundation
    url: https://jnaf.ca

status-website:
  themeUrl: https://rawcdn.githack.com/TMRRWinc/status/c2bb1212584301155568e62f082d67ea3154f45b/assets/css/tmrrw.css
  cname: uptime.tmrrwinc.com
  logoUrl: https://uploads-ssl.webflow.com/62d03a0ddfe41e0b5dca9c5b/62d03a0ddfe41e8104ca9c9b_footer-logo.svg
  name: Website Uptime Monitoring
  introTitle: "**TMRRW Inc. Uptime Monitor** is a powerful tool that ensures the continuous availability and performance of our services"
  introMessage: With real-time data updates, you can stay informed about any issues or downtime that may occur. Our uptime monitor helps us strive for optimal service reliability.
  navbar:
    - title: Status
      href: /
    - title: Support
      href: https://tmrrwinc.com/support

i18n:
  footer: This page is [open source](https://tmrrwinc.com), powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
